version: "3.9"
services:
  bot:
    build: .
    volumes:
        - "./:/DigitalBeing"
    ports:
        - "65535:65535"

  db:
    restart: always
    image: postgres
    hostname: digitalbeing_db
    environment:
      POSTGRES_DB: digitalbeing
      POSTGRES_USER: digitalbeing
      POSTGRES_PASSWORD: digitalbeing_default_pw
    ports:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  editor:
    build: .
    restart: always
    command: ./editor.sh
    volumes:
        - "./:/DigitalBeing"
    environment:
      PGHOST: digitalbeing_db
      PGUSER: digitalbeing
      PGPASSWORD: digitalbeing_default_pw
      PGDATABASE: digitalbeing
    ports:
      - "7777:7777"